### ISSUE TITLE
[Q] does ssham create user on host?

### ISSUE THREAD

**Issue by Kinmarui** [pacoorozco/ssham#16]
As in title, if user don't exist on host but I add host to group in ssham which has assigned couple of people will ssham create account for them ?

I tried to look in repo and found https://github.com/pacoorozco/ssham/blob/master/app/Console/Commands/SendKeysToHosts.php but it don't indicates that such feature exists.

@pacoorozco 
tbh i'm surprised there is no decent tool providing ssh key management access. Since you didn't updated this project in 3 years, is it reached good enough stage or maybe you are using something different?

**Comment by pacoorozco** [comment]
Hi @Kinmarui 
It's very nice to have questions about this project...

First question, when you create a host in SSHAM you need to specify a valid user. That means that **this user has been created in the host before**. This user will be used by SSHAM users to access in. The most common scenario is using `root` account, but some people use SSHAM to access to developer user or similar.

In my case, I had a lot of hosts (more than 200) and a group of sysops (20+). And we access to the hosts with `root` account using SSH keys. This way, when ppl leaved the company we only need to revoke SSH key though SSHAM. 

Regarding second question... You're right, It's difficult to find a good tool to deal with SSH keys. I think lof ot ppl goes for a different way, that is creating users accounts in hosts (with sudo permission) with Puppet or Ansible. 

The reason of why this repo has not been maintained is that I changed my job over a year ago. In my new job we don't need this way to access, we are using inmutable instances. But, this is a good side project so I'd like to spent time on it if it's worthy for anyone. 

If you had any doubt / comment or you want to collaborate, just ask :-D

Thanks
Paco

**Comment by Kinmarui** [comment]
Hi @pacoorozco 

So main thing I still don't understand is does SSHAM act like proxy and all request go through this server or  does it need to have root access to host and then when I add user to group to which host belong ssh public key will be added for that user. I was under impression that it is latter. And then my question is does SSHAM create account on that machine (using account provided when host was configured) that will match user configuration in SSHAM.

How I would see it (am I correct)
1. I add host to SSHAM (I need to provide private key to that account? or should I add public key from SSHAM to every user I want to use as 'managing account')
2. I add users to SSHAM (I add their public keys and assign usernames)
3. I assign host in groups and user in groups
4. When I assign user to host (directly or by group assignment) it will create account for given user and copy that user public key to that account

Tbh I have much smaller team and number of hosts then you described (4 people, 10+ hosts) but just found annoying fact that I need to create manually accounts and copy keys for each new machine. sometimes we add temporary machines and this make it feel event more tedious and repetitive.

**Comment by pacoorozco** [comment]
Hi @Kinmarui 

You are almost right, but let me to repeat in my own words :-D

1. Add a host to SSHAM, it should belong to a **host group** (e.g. servers_in_pre). You need to supply a **hostname + username** (e.g. admin@server.domain.com). SSHAM will use a configured private key (see _SSHAM settings_) to connect to this hostname (server.domain.com) with the supplied user (admin). This **username** is going to be the one that  SSHAM users will have access to.

> Note: In order to SSHAM was able to connect to the host, you have had to configure SSHAM public key as authorized to connect to the user account in the host.

1. Create a SSHAM user (it's not a **host** user, e.g. kinmarui ) and generate SSH keys. Public key will remain in SSHAM database. Private one is downloaded, keep it safe because this key will be used as auth to connect to **hosts**. Let's imagine we assign this user to a user group (e.g. developers).

1. Assign permissions to allow a **user gorup** (developers) access to a **host group** (servers_in_pre). SSHAM will copy SSH public keys to user authorized keys file in each host in the specified **host group**.

1. From now, every SSHAM user in **user group** can access to every server in **host group** using the specified host user (admin). So, from your workstation you can do:

```
$ ssh admin@server.domain.com -i ~/path/to/downloaded_private_key
```
This way SSHAM users could access to PRE servers with its own SSH keys. When an current user doesn't need access to the host, you can revoke the access or, if needed, revoke the key. As far as you doesn't share any password with users, you will be fine :-D

It's now clear? I think I need to document this somewhere

Paco
