### ISSUE TITLE
Upgrade from 0.16 to current

### ISSUE THREAD

**Issue by MrCr0a** [pacoorozco/ssham#472]
Hello, 

First of all thank you for making SSHAM, it's a useful tool. I would like to know if there's is a way to upgrade from 0.16.0 to current version without reinstalling the software from scratch. I think there was some change made in the database table.

Thanks

Have a nice day

**Comment by pacoorozco** [comment]
Hi!

Since version 0.17.0 the database changed in a non-backwards-compatible way. So I'm afraid that you have to reinstall and migrate the data manually. I'm sorry, but this project is still under active development.

If you have a lot of data to migrate, let's talk a see if we can work on it together.
